name: 'Build godot templates'
description: 'Build godot templates with encryption key'

inputs:
  platform:
    description: Target platform.
    required: true
  version:
    description: 'Godot version'
    required: true
    default: '4.3'
  encryption-key:
    description: 'Encryption key for templates'
    required: true
  
outputs:
  file:
    description: 'Path to the generated template file'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.version }}
    - ${{ inputs.platform }}
    - ${{ inputs.encryption-key }}